import type {
  TicketItem,
  OrgTeamOption,
  OrgMemberOption,
  TicketTag,
} from './types'

export const MOCK_TEAMS: readonly OrgTeamOption[] = [
  { id: 1, name: 'Support Tier 1', memberIds: [1, 2, 3] },
  { id: 2, name: 'Billing Support', memberIds: [1, 4] },
  { id: 3, name: 'Security Operations', memberIds: [1, 5] },
]

export const MOCK_MEMBERS: readonly OrgMemberOption[] = [
  { id: 1, name: 'Acme Admin', email: 'admin@acme.test', role: 'admin', teamIds: [1, 2, 3] },
  { id: 2, name: 'Acme Agent', email: 'agent@acme.test', role: 'agent', teamIds: [1] },
  { id: 3, name: 'Sarah Chen', email: 'sarah.chen@acme.test', role: 'agent', teamIds: [1] },
  { id: 4, name: 'Marcus Brody', email: 'marcus.b@acme.test', role: 'agent', teamIds: [2] },
  { id: 5, name: 'Alex Rivera', email: 'alex.r@acme.test', role: 'agent', teamIds: [3] },
]

export const MOCK_TAGS_POOL: readonly TicketTag[] = [
  { id: 1, name: 'security', slug: 'security', color: '#F43F5E' },
  { id: 2, name: 'p0-escalation', slug: 'p0-escalation', color: '#EF4444' },
  { id: 3, name: 'auth-v2', slug: 'auth-v2', color: '#64748B' },
  { id: 4, name: 'database', slug: 'database', color: '#3B82F6' },
  { id: 5, name: 'performance', slug: 'performance', color: '#F59E0B' },
  { id: 6, name: 'billing', slug: 'billing', color: '#10B981' },
  { id: 7, name: 'portal', slug: 'portal', color: '#475569' },
  { id: 8, name: 'api', slug: 'api', color: '#EC4899' },
  { id: 9, name: 'compliance', slug: 'compliance', color: '#06B6D4' },
]

export const INITIAL_MOCK_TICKETS: readonly TicketItem[] = [
  {
    id: 'ticket-1',
    organization_id: 1,
    ticket_number: 1001,
    subject: 'Vulnerability report: Potential SSO replay issue with SAML assertions',
    status: 'new',
    priority: 'urgent',
    customer: {
      id: 'cust-1',
      name: 'Alice Freeman',
      email: 'alice@example.com',
      tier: 'Enterprise',
      total_inquiries: 4,
      company: 'Acme Partner Solutions',
    },
    assigned_team_id: null,
    assigned_team_name: null,
    assigned_member_id: null,
    assigned_member_name: null,
    tags: [
      { id: 1, name: 'security', slug: 'security', color: '#F43F5E' },
      { id: 2, name: 'p0-escalation', slug: 'p0-escalation', color: '#EF4444' },
      { id: 3, name: 'auth-v2', slug: 'auth-v2', color: '#64748B' },
    ],
    messages: [
      {
        id: 'msg-1',
        ticket_id: 'ticket-1',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Alice Freeman',
        author_email: 'alice@example.com',
        body: 'During our automated perimeter penetration test, our security tooling detected that the SAML 2.0 assertion artifact could theoretically be reused within a 5-minute clock drift window without being invalidated in cache. Attached is our sanitized HTTP trace capture and initial audit finding summary. Please escalate to the security engineering team.',
        attachments: [
          {
            id: 'att-1',
            file_name: 'saml-replay-poc.har',
            file_size_bytes: 2516582,
            mime_type: 'application/json',
          },
          {
            id: 'att-2',
            file_name: 'security-audit-summary.pdf',
            file_size_bytes: 1887436,
            mime_type: 'application/pdf',
          },
        ],
        created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-2',
        ticket_id: 'ticket-1',
        message_type: 'internal_note',
        author_type: 'OrganizationMember',
        author_name: 'Alex Rivera',
        author_email: 'alex.r@acme.test',
        author_role: 'Security Engineer',
        body: 'I verified the clock skew tolerance in AuthServiceProvider. Currently `allowed_clock_skew_seconds` is set to 300. We need to clamp this to 30 seconds and introduce a transient Redis atomic replay key with an eviction TTL. Claiming this ticket to prepare a patch.',
        attachments: [],
        created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-1',
        ticket_id: 'ticket-1',
        team_id: null,
        member_id: null,
        assigned_by_name: 'System Intake',
        created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        note: 'Ticket ingested via Customer Portal form',
      },
    ],
    created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-2',
    organization_id: 1,
    ticket_number: 1002,
    subject: 'Database query timeout on batch analytics export',
    status: 'open',
    priority: 'high',
    customer: {
      id: 'cust-2',
      name: 'Bob Smith',
      email: 'bob@example.com',
      tier: 'Growth',
      total_inquiries: 12,
      company: 'Tech Solutions Inc.',
    },
    assigned_team_id: 1,
    assigned_team_name: 'Support Tier 1',
    assigned_member_id: 2,
    assigned_member_name: 'Acme Agent',
    tags: [
      { id: 4, name: 'database', slug: 'database', color: '#3B82F6' },
      { id: 5, name: 'performance', slug: 'performance', color: '#F59E0B' },
    ],
    messages: [
      {
        id: 'msg-3',
        ticket_id: 'ticket-2',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Bob Smith',
        author_email: 'bob@example.com',
        body: 'Whenever we trigger the monthly ledger report export for datasets with more than 50,000 rows, the request stalls for 60 seconds and returns an HTTP 504 Gateway Timeout error. Is there an active maintenance or database degradation occurring right now?',
        attachments: [],
        created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-4',
        ticket_id: 'ticket-2',
        message_type: 'internal_note',
        author_type: 'OrganizationMember',
        author_name: 'Acme Agent',
        author_email: 'agent@acme.test',
        author_role: 'Support Agent',
        body: 'Checked pg_stat_activity on the read replica. The query is performing a sequential scan over `ticket_messages` because of an unindexed compound predicate `(organization_id, created_at)`. Sent an alert to DB operations.',
        attachments: [],
        created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-5',
        ticket_id: 'ticket-2',
        message_type: 'public_reply',
        author_type: 'OrganizationMember',
        author_name: 'Acme Agent',
        author_email: 'agent@acme.test',
        author_role: 'Support Agent',
        body: 'Hello Bob, thank you for reaching out. We have pinpointed the query plan bottleneck. Our infrastructure engineers are rolling out a targeted index on the reporting table to resolve the timeout. While that migration executes, you can export data in 10,000-row intervals without encountering timeouts.',
        attachments: [],
        created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-2',
        ticket_id: 'ticket-2',
        team_id: 1,
        team_name: 'Support Tier 1',
        member_id: 2,
        member_name: 'Acme Agent',
        assigned_by_name: 'Acme Admin',
        created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
        note: 'Assigned to Support Tier 1',
      },
    ],
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-3',
    organization_id: 1,
    ticket_number: 1003,
    subject: 'Dark mode support and custom CSS for customer portal',
    status: 'pending',
    priority: 'low',
    customer: {
      id: 'cust-3',
      name: 'Diana Prince',
      email: 'diana@example.com',
      tier: 'Pro',
      total_inquiries: 3,
      company: 'Themyscira Ltd',
    },
    assigned_team_id: 1,
    assigned_team_name: 'Support Tier 1',
    assigned_member_id: 2,
    assigned_member_name: 'Acme Agent',
    tags: [
      { id: 7, name: 'portal', slug: 'portal', color: '#475569' },
    ],
    messages: [
      {
        id: 'msg-6',
        ticket_id: 'ticket-3',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Diana Prince',
        author_email: 'diana@example.com',
        body: 'Hi team, is there any roadmap item or setting to enable dark mode or apply custom CSS tokens for the customer portal view? Our operations team uses the portal in low-light environments.',
        attachments: [],
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-7',
        ticket_id: 'ticket-3',
        message_type: 'public_reply',
        author_type: 'OrganizationMember',
        author_name: 'Acme Agent',
        author_email: 'agent@acme.test',
        author_role: 'Support Agent',
        body: 'Hi Diana! While the Customer Portal currently defaults to the clean Warm Alabaster theme, customizable dark mode theming is slated for our upcoming Stage 3 release. Would you like us to enroll your organization in our early design sandbox?',
        attachments: [],
        created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-8',
        ticket_id: 'ticket-3',
        message_type: 'internal_note',
        author_type: 'OrganizationMember',
        author_name: 'Sarah Chen',
        author_email: 'sarah.chen@acme.test',
        author_role: 'Support Agent',
        body: 'Awaiting Diana confirmation before adding her tenant slug to the feature flag cohort.',
        attachments: [],
        created_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-3',
        ticket_id: 'ticket-3',
        team_id: 1,
        team_name: 'Support Tier 1',
        member_id: 2,
        member_name: 'Acme Agent',
        assigned_by_name: 'System Auto-Route',
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-1004',
    organization_id: 1,
    ticket_number: 1004,
    subject: 'Billing discrepancy on invoice #INV-2026-09',
    status: 'open',
    priority: 'high',
    customer: {
      id: 'cust-4',
      name: 'Marcus Vance',
      email: 'marcus.vance@apex.io',
      tier: 'Enterprise',
      total_inquiries: 7,
      company: 'Apex Logistics Corp',
    },
    assigned_team_id: 2,
    assigned_team_name: 'Billing Support',
    assigned_member_id: 1,
    assigned_member_name: 'Acme Admin',
    tags: [
      { id: 6, name: 'billing', slug: 'billing', color: '#10B981' },
    ],
    messages: [
      {
        id: 'msg-9',
        ticket_id: 'ticket-1004',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Marcus Vance',
        author_email: 'marcus.vance@apex.io',
        body: 'Our accounts payable team noticed that invoice #INV-2026-09 includes charges for 25 agent seats, whereas 5 seats were formally decommissioned on September 14th. Please issue a credit note for the prorated difference.',
        attachments: [
          {
            id: 'att-3',
            file_name: 'invoice-INV-2026-09.pdf',
            file_size_bytes: 348160,
            mime_type: 'application/pdf',
          },
        ],
        created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-10',
        ticket_id: 'ticket-1004',
        message_type: 'internal_note',
        author_type: 'OrganizationMember',
        author_name: 'Acme Admin',
        author_email: 'admin@acme.test',
        author_role: 'Administrator',
        body: 'Stripe subscription records confirm the seat reduction on Sept 14. Calculating prorated credit: $142.50 to be credited on invoice #INV-2026-10.',
        attachments: [],
        created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-4',
        ticket_id: 'ticket-1004',
        team_id: 2,
        team_name: 'Billing Support',
        member_id: 1,
        member_name: 'Acme Admin',
        assigned_by_name: 'Marcus Brody',
        created_at: new Date(Date.now() - 170 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-1005',
    organization_id: 1,
    ticket_number: 1005,
    subject: 'API Webhook delivery failure (HTTP 429 Too Many Requests)',
    status: 'new',
    priority: 'urgent',
    customer: {
      id: 'cust-5',
      name: 'Sarah Jenkins',
      email: 'sarah.j@finflow.co',
      tier: 'Enterprise',
      total_inquiries: 1,
      company: 'FinFlow Systems',
    },
    assigned_team_id: null,
    assigned_team_name: null,
    assigned_member_id: null,
    assigned_member_name: null,
    tags: [
      { id: 8, name: 'api', slug: 'api', color: '#EC4899' },
      { id: 2, name: 'p0-escalation', slug: 'p0-escalation', color: '#EF4444' },
    ],
    messages: [
      {
        id: 'msg-11',
        ticket_id: 'ticket-1005',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Sarah Jenkins',
        author_email: 'sarah.j@finflow.co',
        body: 'Our inbound webhook receiver at `https://api.finflow.co/hooks/zeddesk` started receiving HTTP 429 errors from your delivery queue during our peak event burst at 04:30 UTC. We need our webhook outbound rate-limit bucket adjusted immediately.',
        attachments: [
          {
            id: 'att-4',
            file_name: 'webhook-retry-errors.log',
            file_size_bytes: 1153433,
            mime_type: 'text/plain',
          },
        ],
        created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-5',
        ticket_id: 'ticket-1005',
        team_id: null,
        member_id: null,
        assigned_by_name: 'System Intake',
        created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-1006',
    organization_id: 1,
    ticket_number: 1006,
    subject: 'Request for SOC2 Type II compliance report & ISO 27001 certificate',
    status: 'resolved',
    priority: 'medium',
    customer: {
      id: 'cust-6',
      name: 'Elena Rostova',
      email: 'elena@globalbank.ch',
      tier: 'Enterprise',
      total_inquiries: 2,
      company: 'Global Bank Zurich',
    },
    assigned_team_id: 3,
    assigned_team_name: 'Security Operations',
    assigned_member_id: 5,
    assigned_member_name: 'Alex Rivera',
    tags: [
      { id: 9, name: 'compliance', slug: 'compliance', color: '#06B6D4' },
      { id: 1, name: 'security', slug: 'security', color: '#F43F5E' },
    ],
    messages: [
      {
        id: 'msg-12',
        ticket_id: 'ticket-1006',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Elena Rostova',
        author_email: 'elena@globalbank.ch',
        body: 'Hello, as part of our annual vendor security compliance audit, please provide your current SOC 2 Type II assurance report along with the ISO/IEC 27001 certificate.',
        attachments: [],
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-13',
        ticket_id: 'ticket-1006',
        message_type: 'internal_note',
        author_type: 'OrganizationMember',
        author_name: 'Alex Rivera',
        author_email: 'alex.r@acme.test',
        author_role: 'Security Engineer',
        body: 'Mutual NDA verified with Global Bank legal team. Cleared for standard SOC 2 packet transmission.',
        attachments: [],
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-14',
        ticket_id: 'ticket-1006',
        message_type: 'public_reply',
        author_type: 'OrganizationMember',
        author_name: 'Alex Rivera',
        author_email: 'alex.r@acme.test',
        author_role: 'Security Engineer',
        body: 'Dear Elena, attached please find the ZedDesk 2026 SOC 2 Type II audit report covering the period October 2025 – September 2026. Please let us know if your procurement team requires any supplementary questionnaires.',
        attachments: [
          {
            id: 'att-5',
            file_name: 'ZedDesk-SOC2-Type-II-2026.pdf',
            file_size_bytes: 4823449,
            mime_type: 'application/pdf',
          },
        ],
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-6',
        ticket_id: 'ticket-1006',
        team_id: 3,
        team_name: 'Security Operations',
        member_id: 5,
        member_name: 'Alex Rivera',
        assigned_by_name: 'Alex Rivera',
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-1007',
    organization_id: 1,
    ticket_number: 1007,
    subject: 'Duplicate organization member invite links expiring prematurely',
    status: 'closed',
    priority: 'medium',
    customer: {
      id: 'cust-7',
      name: 'Carlos Mendez',
      email: 'carlos@techcorp.es',
      tier: 'Growth',
      total_inquiries: 8,
      company: 'TechCorp Europe',
    },
    assigned_team_id: 1,
    assigned_team_name: 'Support Tier 1',
    assigned_member_id: 2,
    assigned_member_name: 'Acme Agent',
    tags: [
      { id: 3, name: 'auth-v2', slug: 'auth-v2', color: '#64748B' },
    ],
    messages: [
      {
        id: 'msg-15',
        ticket_id: 'ticket-1007',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Carlos Mendez',
        author_email: 'carlos@techcorp.es',
        body: 'When sending invitations to new developers in our organization, the link claims to have expired within 10 minutes instead of the configured 48-hour grace window.',
        attachments: [],
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-16',
        ticket_id: 'ticket-1007',
        message_type: 'public_reply',
        author_type: 'OrganizationMember',
        author_name: 'Acme Agent',
        author_email: 'agent@acme.test',
        author_role: 'Support Agent',
        body: 'Hi Carlos, we identified an issue where resending an invite regenerated a token that immediately marked the prior pending record as stale. We deployed a fix so multiple links remain valid until accepted. Could you test resending?',
        attachments: [],
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'msg-17',
        ticket_id: 'ticket-1007',
        message_type: 'public_reply',
        author_type: 'Customer',
        author_name: 'Carlos Mendez',
        author_email: 'carlos@techcorp.es',
        body: 'Confirmed that the new invite link worked seamlessly for both new members. Thank you!',
        attachments: [],
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    assignments: [
      {
        id: 'asg-7',
        ticket_id: 'ticket-1007',
        team_id: 1,
        team_name: 'Support Tier 1',
        member_id: 2,
        member_name: 'Acme Agent',
        assigned_by_name: 'Acme Agent',
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
