/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-canvas': '#0B0F19',
        'canvas-base': '#0B0F19',
        'surface-panel': '#0F172A',
        'surface-subpanel': '#1E293B',
        'surface-container': '#171F33',
        'surface-container-low': '#131B2E',
        'surface-container-high': '#222A3D',
        'surface-container-highest': '#2D3449',
        'surface-container-lowest': '#060E20',
        'container-low': '#131B2E',
        'container-high': '#222A3D',
        'container-highest': '#2D3449',
        'container-lowest': '#060E20',
        'border-subtle': '#1E293B',
        'border-prominent': '#334155',
        'primary-container': '#4F46E5',
        'primary-dark': '#4338CA',
        'inverse-primary': '#4D44E3',
        'accent-glow': '#6366F1',
        'accent-indigo-glow': '#6366F1',
        'secondary': '#8B5CF6',
        'secondary-light': '#D0BCFF',
        'sentiment-positive': '#10B981',
        'sentiment-neutral': '#94A3B8',
        'sentiment-warning': '#F59E0B',
        'sentiment-negative': '#F43F5E',
        'sentiment-critical': '#F43F5E',
        'ai-confidence-high': '#10B981',
        'ai-confidence-medium': '#F59E0B',
        'ai-confidence-low': '#EF4444',
        'workflow-n8n-orange': '#FF6D5A',
        'on-surface': '#F8FAFC',
        'on-surface-variant': '#94A3B8',
        'text-primary': '#F8FAFC',
        'text-secondary': '#94A3B8',
        'text-muted': '#64748B',
        'outline': '#64748B',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        'gutter': '16px',
        'header-height': '64px',
      },
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.010em', fontWeight: '600' }],
        'body-default': ['13px', { lineHeight: '19px', letterSpacing: '0em', fontWeight: '400' }],
        'body-compact': ['12px', { lineHeight: '17px', letterSpacing: '0em', fontWeight: '400' }],
        'title-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'mono-data': ['12px', { lineHeight: '16px', letterSpacing: '-0.020em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.050em', fontWeight: '600' }],
        'label-regular': ['12px', { lineHeight: '16px', letterSpacing: '0.010em', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Inter', 'ui-monospace', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-default': ['Inter', 'sans-serif'],
        'body-compact': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'mono-data': ['Inter', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'label-regular': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem', // 4px
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',        // 8px
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'keylight': 'inset 0 1px 0 rgba(255, 255, 255, 0.06)',
        'keylight-primary': 'inset 0 1px 0 rgba(255, 255, 255, 0.20)',
        'modal': '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.5)',
        'luminous-indigo': '0 0 0 1px #4F46E5, 0 0 12px rgba(99, 102, 241, 0.35)',
      },
    },
  },
  plugins: [],
}
