/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-canvas': '#0F1012',
        'canvas-base': '#0F1012',
        'surface-panel': '#16181C',
        'surface-subpanel': '#1E2026',
        'surface-container': '#1E2026',
        'surface-container-low': '#16181C',
        'surface-container-high': '#22242B',
        'surface-container-highest': '#282A33',
        'surface-container-lowest': '#0F1012',
        'container-low': '#16181C',
        'container-high': '#22242B',
        'container-highest': '#282A33',
        'container-lowest': '#0F1012',
        'border-subtle': '#282A33',
        'border-prominent': '#3B3F4D',
        'primary-container': '#F59E0B',
        'primary-dark': '#D97706',
        'inverse-primary': '#FBBF24',
        'accent-glow': '#F59E0B',
        'accent-indigo-glow': '#8B5CF6',
        'accent-ai': '#8B5CF6',
        'secondary': '#8B5CF6',
        'secondary-light': '#D0BCFF',
        'sentiment-positive': '#10B981',
        'sentiment-neutral': '#8890A0',
        'sentiment-warning': '#F59E0B',
        'sentiment-negative': '#F43F5E',
        'sentiment-critical': '#F43F5E',
        'ai-confidence-high': '#10B981',
        'ai-confidence-medium': '#F59E0B',
        'ai-confidence-low': '#EF4444',
        'workflow-n8n-orange': '#FF6D5A',
        'on-surface': '#F1F3F7',
        'on-surface-variant': '#8890A0',
        'text-primary': '#F1F3F7',
        'text-secondary': '#8890A0',
        'text-muted': '#525866',
        'outline': '#525866',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        'gutter': '16px',
        'header-height': '64px',
      },
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.010em', fontWeight: '600' }],
        'body-default': ['13px', { lineHeight: '19px', letterSpacing: '0em', fontWeight: '400' }],
        'body-compact': ['12px', { lineHeight: '17px', letterSpacing: '0em', fontWeight: '400' }],
        'title-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'mono-data': ['12px', { lineHeight: '16px', letterSpacing: '-0.020em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.050em', fontWeight: '600' }],
        'label-regular': ['12px', { lineHeight: '16px', letterSpacing: '0.010em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '17px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.010em', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Inter', 'ui-monospace', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-default': ['Inter', 'sans-serif'],
        'body-compact': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'mono-data': ['JetBrains Mono', 'Inter', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'label-regular': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem', // 4px
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',        // 8px
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'keylight': 'inset 0 1px 0 rgba(255, 255, 255, 0.08)',
        'keylight-primary': 'inset 0 1px 0 rgba(255, 255, 255, 0.25)',
        'card': 'inset 0 1px 0 rgba(255, 255, 255, 0.08)',
        'modal': '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.5)',
        'luminous-amber': '0 0 0 1px #F59E0B, 0 0 12px rgba(245, 158, 11, 0.35)',
        'luminous-indigo': '0 0 0 1px #8B5CF6, 0 0 12px rgba(139, 92, 246, 0.35)',
      },
    },
  },
  plugins: [],
}
